<?
global $language;
	
$language = array();
	
$language[0] = "";
$language[1] = "Sehr geehrte(r) Interessent(in),

bitte bestätigen Sie durch einen Klick auf den folgenden Link Ihren Wunsch, unsere Newsletter künftig zu erhalten.

Vielen Dank.

<!-- link -->

(Falls Ihr Email-Programm die vorstehende Adresse nicht als Link interpretiert, tragen Sie bitte die komplette Adresse ohne Leerzeichen in die Adresszeile Ihres Browser und bestätigen Sie mit Enter. Vielen Dank) 

Mit freundlichen Grüßen

LANDESAPOTHEKERKAMMER HESSEN
Körperschaft des öffentlichen Rechts
Kuhwaldstraße 46
60486 Frankfurt am Main
E-Mail: info@apothekerkammer.de

Besuchen Sie uns auch im Internet unter: www.apothekerkammer.de";
$language[2] = "<p>Vielen Dank für Ihre Anmeldung. Sie erhalten in Kürze eine E-Mail von uns.
<b>Bitte bestätigen Sie Ihre Newsletter-Anmeldung durch Klick auf den im E-Mail enthaltenen link!</b>

Wir freuen uns darauf, zukünftig interessante Neuigkeiten mit Ihnen zu teilen!

Mit freundlichen Grüßen

Ihre
LANDESAPOTHEKERKAMMER HESSEN</p>";
$language[3] = "Herr
Frau
Herr Dr.
Frau Dr.";
$language[4] = "<p>Bitte wählen Sie Ihre gewünschten Newsletter aus folgenden Themen aus:</p>";
$language[5] = "Pflichtfelder";
$language[6] = "Bitte bestätigen Sie Ihre Newsletter-Anmeldung";
$language[7] = "LAK Hessen: Newsletter Bestätigung";
$language[8] = "info@apothekerkammer.de";
$language[9] = "<h2>Newsletter-Aktivierung</h2>
<p>Vielen Dank für Ihre Anmeldung.
Sie erhalten zukünftig die gewählten Newsletter an die von Ihnen angegebene E-Mail-Adresse.</p>";
$language[10] = "<h2>Newsletter Abbestellen</h2><p>Ihre Abmeldung war erfolgreich</p>";
$language[11] = "<h2>Newsletter Abbestellen</h2><p>Wir konnten Ihre Adresse in unserem System nicht finden</p>";
$language[12] = "<p>Die gewählten Themen/Newsletter sollen gesendet werden an:</p>";
$language[13] = "<p><a href=\"unregister.php\">Bitte klicken Sie hier, wenn Sie unseren Newsletter <b>abbestellen</b> möchten.</a></p>";
	?>