<?php  $nav = '
				<li class="nav-item n3n xx3xx"><a href="http://localhost/your-plate/" class="nav-link ">Startseite / Zeile 1 / 3 Spalten</a></li>
				<li class="nav-item tabletOff n1n xx1xx"><a href="http://localhost/your-plate/" class="nav-link ">Kontakt</a></li>
				<li class="nav-item n2n xx2xx"><a href="http://localhost/your-plate/vorher-nachher/" class="nav-link ">Vorher Nachher</a></li>
				<li class="nav-item n4n xx4xx"><a href="http://localhost/your-plate/faq/" class="nav-link ">FAQ</a></li>
				<li class="nav-item n5n xx5xx"><a href="http://localhost/your-plate/dsgvo-datenschutzrechtliche/" class="nav-link ">DSGVO Datenschutzrechtliche</a></li>
				<li class="nav-item n6n xx6xx"><a href="http://localhost/your-plate/impressum/" class="nav-link ">Impressum</a></li>
				<li class="nav-item n7n xx7xx"><a href="http://localhost/your-plate/widerruf/" class="nav-link ">Widerruf</a></li>
				<li class="nav-item n8n xx8xx"><a href="http://localhost/your-plate/agb/" class="nav-link ">AGB</a></li>
				<li class="nav-item n9n xx9xx"><a href="http://localhost/your-plate/versandinformation/" class="nav-link ">Versandinformation</a></li>

';
?>
